apiVersion: v1
kind: Service
metadata:
  name: connectors-api-loadbalancer
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: sentinel-connectors-api
spec:
  type: LoadBalancer
  selector:
    app: connectors-api
  ports:
  - name: http
    port: 80
    targetPort: 6001