apiVersion: v1
kind: Service
metadata:
  name: workspace-metadata-service
spec:
  type: ClusterIP
  selector:
    app: workspace-metadata-service
  ports:
  - name: http
    port: 80
    targetPort: 6000
